# Generated by Django 2.1.3 on 2018-11-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='business_id',
            field=models.CharField(default='BUSINESS_ID', max_length=50),
        ),
    ]
